# Python 基础

## Python 中的数据集合类

- list 列表 []
- tuple 元组 ()
- set 集合 {}


In [1]:
2+2

4

In [2]:
def f(x):
    return x*x

In [3]:
for i in range(0,10):
    print(f(i))

0
1
4
9
16
25
36
49
64
81


In [4]:
from math import pi

In [5]:
pi

3.141592653589793

In [6]:
import math
math.pi

3.141592653589793

### 随机数

In [7]:
import random

In [8]:
random.randint(0,10)

8

列表

In [9]:
months = ["January","February","March"]

In [10]:
months[0]

'January'

In [11]:
months[1]

'February'

In [12]:
months[2]

'March'

解包

In [13]:
j,f,m = months

In [14]:
j

'January'

In [15]:
f

'February'

In [16]:
m

'March'

## 拼接

In [17]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

列表索引和切片

切片： 两个索引之间的所有值构成的列表

In [18]:
months[1:3]

['February', 'March']

In [19]:
nums = [0,1,2,3,4,5,6,7,8,9,10]
nums[2:6] # 从索引2至6 (不含6)的切片

[2, 3, 4, 5]

`len` 计算列表的长度

In [20]:
len(months) 

3

In [21]:
nums[len(nums)-1] # nums 的最后一项

10

In [22]:
nums[-1] # nums 的最后一项

10

In [23]:
nums[3:] # 返回索引从3开始到结束的列表

[3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
nums[3:-2] # 返回索引从3开始到倒数第2个的列表

[3, 4, 5, 6, 7, 8]

迭代列表

In [25]:
for x in months:
    print('Month: '+x)

Month: January
Month: February
Month: March


In [26]:
squares = []
for n in nums:
    squares.append(n*n)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## 列表推导式

迭代地构建列表

In [27]:
[x*x for x in nums]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [28]:
years = [2018,2019,2020]
[m +' '+ str(y) for y in years for m in months]

['January 2018',
 'February 2018',
 'March 2018',
 'January 2019',
 'February 2019',
 'March 2019',
 'January 2020',
 'February 2020',
 'March 2020']

In [29]:
[ [m + " " + str(y) for y in years] for m in months ]

[['January 2018', 'January 2019', 'January 2020'],
 ['February 2018', 'February 2019', 'February 2020'],
 ['March 2018', 'March 2019', 'March 2020']]

range

In [30]:
range(5,10)  # range 不是列表，但可以迭代

range(5, 10)

In [31]:
for i in range(5,10):
    print(i)

5
6
7
8
9


In [32]:
list(range(5,10)) # 使用 list 函数， 将 range 转换成 list

[5, 6, 7, 8, 9]

In [33]:
list(range(10)) # 只传一个值，自动从零开始，计数到输入的数

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
list(range(0,10,3)) #  第三个参数为增量

[0, 3, 6, 9]

## zip
zip 函数：接收两个长度相同的可迭代对象，并返回由第一个和第二个对象的对应条目组成的可迭代对象

In [35]:
z = zip([1,2,3],["a","b","c"])

In [36]:
z # zip 函数的值支持迭代，但是不支持索引

In [37]:
list(z)  # 一旦迭代过一个zip，它就不在那里了。（不能重复执行）最好将它转换成列表

[(1, 'a'), (2, 'b'), (3, 'c')]

## 生成器
Python 的生成器提供了一种创建可迭代对象的方法，它不是一次性存储所有的值，而是存储指令来产生值。


区别在于生成器可以产生许多值，而函数最多返回一次，然后就结束了。

In [38]:
def count():
    x = 0
    while True:
        yield x
        x+=1
## 这是一个无限的序列，但count() 并不会让计算机崩溃。这是因为它只返回一个生成器对象，而不是一个完整的值列表。

In [39]:
count()

<generator object count at 0x000001B4E0D07280>

In [40]:
for x in count():
    if x>20:
        break
    else:
        print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [41]:
def count2(a,b):
    x = a
    while x < b:
        yield x
        x += 1

In [42]:
count2(10,20)

<generator object count2 at 0x000001B4E0FA8930>

In [43]:
[x for x in count2(10,20)]

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [44]:
( x * x for x in range(0,10)) # 生成器推导式，这个生成器产生数字 0 到 9 的平方

<generator object <genexpr> at 0x000001B4E0FA9080>

In [45]:
def square(a):
    for x in range(0,a):
        yield x*x

list(square(10))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## 元组 (tuple)

元组是与列表很相似的可迭代对象。但元组是不可变（immutable）的：一旦创建，就不能更改，也意味着元组没有 append 方法。使用圆括号声明，或者不用括号

zip 函数的条目实际上也是元组，元组在某种意义上是 Python 中的默认集合类

```python
a=1,2,3,4,5 # a 会被解析为这些数的元组
```

如果用 `return a,b` 结束一个函数， 实际输出的元组 `(a,b)`

内置函数 `tuple()` 将可迭代对象转换成元组

In [46]:
(1,2)

(1, 2)

In [47]:
("a","b","c")

('a', 'b', 'c')

In [48]:
1,2,3,4

(1, 2, 3, 4)

In [49]:
"a","b","c"

('a', 'b', 'c')

## 集合 （set）

集合（set）是每个条目都必须不同且无序，是使用花括号包裹，逗号隔开的条目的列表，与数学中的写法一致。

将列表转换成集合，可以便捷地确保没有重复值。

内置函数 `set()` 将可迭代对象转换成集合

集合是无序的，所以如果两个集合的条目完全相等，那么他们相等。

In [50]:
dups = [1,2,3,3,3,4,4,5,5,6,7,8,9,9]

set(dups)

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [51]:
set([1,2,3,2,3]) == set([3,2,1])

True

## NumPy 数组

不是Python内置，是来自 Numpy 包

需要安装 NumPy，如果未安装，终端执行 `pip install numpy` 安装

导入 numpy 包

```python
import numpy as np
```

In [52]:
import numpy as np

In [53]:
# 创建 NumPy数组
# np.array 接收一个可迭代对象

np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

np.arange 与内置 range 工作方式相似

np.arange 生成的是numpy数组，第三个参数可以是一个浮点数 

range 生成的 range对象

In [54]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [56]:
list(range(0,10,2))
# list(range(0,10,1.1)) # 出错

[0, 2, 4, 6, 8]

## 字典

字典是一种工作方式与列表、元组和生成器完全不同的集合类。字典是用键（key）来访问的条目，而不是通过数字索引来访问

In [57]:
dog = {"name": "melba", "age": 2}

In [58]:
dog

{'name': 'melba', 'age': 2}

In [59]:
dog['name']

'melba'

In [60]:
dog['age']

2

## 集合函数

`len()`

`zip()`

`sum()`

`max()`

`min()`

`sorted()` 返回一个可迭代对象经过排序的列表副本

`reversed()` 返回一个给定可迭代对象的反转版本，原始数据不受影响。返回的是一个可迭代对象，但不是列表，需要用 `list()` 函数转换


In [61]:
q = [3,4,1,2,5]

In [62]:
q

[3, 4, 1, 2, 5]

In [63]:
sorted(q)

[1, 2, 3, 4, 5]

In [64]:
q

[3, 4, 1, 2, 5]

In [65]:
reversed(q)

In [66]:
list(reversed(q))

[5, 2, 1, 4, 3]

In [67]:
# 对列表原地排序或反转使用 list 的方法

q.sort()

In [68]:
q

[1, 2, 3, 4, 5]

In [69]:
q.reverse()

In [70]:
q

[5, 4, 3, 2, 1]

## 使用函数

In [71]:
def squate(x):
    y = x*x
    return y

In [72]:
squate(5)

25

In [73]:
# 可变数量的参数
# 加一个星号函数参数，是一个元组
def add (*args):
    total = 0
    for x in args:
        total += x
    return total

In [74]:
add(1,2,3)

6

In [75]:
add(1,2,3,4,5)

15

In [76]:
## 命名参数  关键字参数

'''
本函数使用字符串格式化运算符 %，用给定的字符串和数分别替换 %s 和 %d

name 和 age 是可选的
name 的默认值是 `friend`


'''

def birthday(name="friend",age=None):
    s = "Happy birthday, %s" %name
    if age:
        s+=", you're %d years old" % age
    return s+"!"

In [77]:
birthday()

'Happy birthday, friend!'

In [78]:
birthday('Melba')  # 可以指定一个不同的名字

'Happy birthday, Melba!'

In [79]:
birthday(name='Melba') # 也可以明确指明设置 name

'Happy birthday, Melba!'

第二个参数，age参数是可选的，默认值 `None`

In [80]:
birthday('Melba', 2)

"Happy birthday, Melba, you're 2 years old!"

In [81]:
birthday(age=2) # age 为第二个关键字参数，当不提供 name 时需要指定 age 的参数名

"Happy birthday, friend, you're 2 years old!"

In [82]:
# birthday(2,'Melba') # 出错

In [83]:
birthday(age=2,name='Melba') # 为所有的参数都指定好名字后，就可以以任意顺序传递它们

"Happy birthday, Melba, you're 2 years old!"

In [84]:
# 参数很多，可以将它们打包成字典，使用 ** 运算符传递给函数



In [85]:
dog = {"name":"Melba","age":2}

In [86]:
dog

{'name': 'Melba', 'age': 2}

In [87]:
birthday(**dog)

"Happy birthday, Melba, you're 2 years old!"

### 作为数据的函数

在Python中，函数是一等公民，意思是可以将它们赋值给变量、传递给函数或作为其他函数的输出值返回。

换句话说，函数看起来就像Python中的任何其他数据一样。

In [88]:
def sq(x):
    return x*x

In [89]:
def evaluate(f,x):
    return f(x)

In [90]:
evaluate(sq,10)

100

map 函数：接收一个函数和一个可迭代对象，将函数应用于原始可迭代对象的每一个条目来扽到新的可迭代对象，并返回

In [91]:
map(sq,range(10))

In [92]:
list(map(sq,range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

记住外部变量并在其定义内使用它的函数称为 **闭包**。


In [93]:
def make_power_function(power):
    def power_function(x):
        return x**power
    return power_function

# 当 make_power_function 完成计算后，返回的 power_function 仍然会记住传递给它的 power 变量

In [94]:
sq2 = make_power_function(2) #平方

In [95]:
sq2(5)

25

In [96]:
cube = make_power_function(3) # 立方

In [97]:
cube(5)

125

## lambda 表达式：匿名函数

一种更简单快速的创建函数的语法。

lambda 关键字可以创建没有名字的函数，称为匿名函数（anonymous function）或 lambda 表达式 来自希腊字母 λ

将函数定义为 lambda 表达式，需要指定一个或多个用逗号隔开的输入变量，后面是冒号和函数的返回值表达式。

任何可以使用函数的地方都能使用lambda 表达式，所有可以直接将它应用于一个值

In [98]:
lambda x:x+2

<function __main__.<lambda>(x)>

In [99]:
(lambda x:x+2)(7)

9

In [100]:
(lambda x,y:x+2*y)(2,3) #接收两个输入变量，并返回第一个变量的值加上第二个变量的两倍

8

对 NumPy 数组应用函数

In [101]:
import numpy as np

np.arange(0,10) # 生成的是numpy数组

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.sqrt(np.arange(0,10)) # 开方

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
def my_function(x):
    if x % 2 ==0:
        return x / 2
    else:
        return 0

In [104]:
my_numpy_funtion = np.vectorize(my_function) # np.vectorize 对 numpy数组的每个条目应用自定义函数

In [105]:
my_numpy_funtion (np.arange(0,10))

array([0., 0., 1., 0., 2., 0., 3., 0., 4., 0.])